// frontend/src/components/ItemCard.tsx
import { Button } from './Button'

interface Item {
    id: string
    name: string
    description: string
    condition: string
    price: number
    image_path?: string
    status?: string
}

interface ItemCardProps {
    item: Item
    onClick?: () => void
    onBuy?: (itemId: string) => void
    isBuying?: boolean
}

export function ItemCard({ item, onClick, onBuy, isBuying = false }: ItemCardProps) {
    const isSold = item.status === 'sold'

    // Parse first image URL
    let imageUrl: string | null = null
    if (item.image_path) {
        try {
            const images = JSON.parse(item.image_path)
            const firstKey = Object.keys(images)[0]
            if (firstKey) {
                imageUrl = images[firstKey]
            }
        } catch { /* ignore */ }
    }

    const handleCardClick = () => {
        if (onClick) onClick()
    }

    const handleBuyClick = (e: React.MouseEvent) => {
        e.stopPropagation() // Prevent card click
        if (onBuy && !isBuying) onBuy(item.id)
    }

    return (
        <div
            className={`cool-card-wrapper group cursor-pointer ${isSold ? 'opacity-60 grayscale' : ''}`}
            onClick={handleCardClick}
        >
            {/* Main Card - No floating accents */}
            <div className="cool-card">
                {/* Top Light Accent */}
                <div className="top-light"></div>

                {/* Image with rounded corners */}
                <div className="cool-card-img-container">
                    {imageUrl ? (
                        <img
                            src={imageUrl}
                            alt={item.name}
                            className="rounded-xl"
                        />
                    ) : (
                        <div className="flex flex-col items-center justify-center text-[var(--text-muted)] w-full h-full rounded-xl bg-[var(--bg-tertiary)]">
                            <span className="text-4xl mb-2">📦</span>
                            <span className="text-sm">No Image</span>
                        </div>
                    )}
                </div>

                {/* Content - Reduced gap with mt-2 */}
                <div className="relative z-10 mt-2">
                    <h3 className="line-clamp-1 text-[var(--text-primary)]" title={item.name}>{item.name}</h3>
                    <span className="price text-[var(--text-primary)]">RM {item.price}</span>

                    <div className="flex items-center justify-between mt-3">
                        {/* Click for details with underline animation */}
                        <span className="text-xs text-[var(--text-secondary)] relative group/link cursor-pointer">
                            Click for details
                            <span className="absolute left-0 bottom-0 w-0 h-[1px] bg-[var(--text-secondary)] transition-all duration-300 group-hover/link:w-full group-hover:w-full" />
                        </span>

                        {!isSold ? (
                            <Button
                                variant="filled"
                                size="sm"
                                className="!rounded-full !px-6 flex items-center gap-2 min-w-[80px] h-8 justify-center transition-colors"
                                onClick={handleBuyClick}
                                disabled={isBuying}
                            >
                                {isBuying ? (
                                    <div className="w-4 h-4 border-2 border-[var(--btn-filled-text)] border-t-transparent rounded-full animate-spin" />
                                ) : (
                                    'Buy'
                                )}
                            </Button>
                        ) : (
                            <span className="text-sm font-bold text-red-400 bg-red-900/30 px-3 py-1 rounded border border-red-500/30">
                                SOLD
                            </span>
                        )}
                    </div>
                </div>
            </div>
        </div>
    )
}

// frontend/app/components/ItemCard.vue
<script setup lang="ts">
interface Item {
  item_id: string
  name: string
  description: string
  condition: string
  images: string // JSON array string or comma separated URLs
  price?: number
  min_price?: number
  status?: string // 'available' or 'sold' or other properties
}

const props = withDefaults(defineProps<{
  item?: Item
  loading?: boolean
}>(), {
  loading: false
})

const imageUrl = computed(() => {
  const item = props.item
  if (!item || !item.images) return '/placeholder.png'
  try {
    const parsed = JSON.parse(item.images)
    if (Array.isArray(parsed) && parsed.length > 0) return parsed[0]
  } catch {
    const split = item.images.split(',')
    if (split.length > 0 && split[0]) return split[0].trim()
  }
  return item.images
})
</script>

<template>
  <div
    v-if="loading"
    class="flex flex-col gap-3 p-3 border border-default rounded-xl"
  >
    <USkeleton class="h-48 w-full rounded-lg" />
    <USkeleton class="h-6 w-3/4 rounded" />
    <div class="flex gap-2">
      <USkeleton class="h-5 w-16 rounded-full" />
      <USkeleton class="h-5 w-20 rounded-full" />
    </div>
    <div class="flex justify-between items-center mt-2">
      <USkeleton class="h-8 w-24 rounded" />
      <USkeleton class="h-8 w-8 rounded-full" />
    </div>
  </div>

  <UCard
    v-else-if="item"
    class="group cursor-pointer transition-all duration-300 flex flex-col overflow-hidden"
    :ui="{ body: 'p-0 flex flex-col flex-1', footer: 'p-3 flex justify-between items-center' }"
    @click="navigateTo(`/items/${item.item_id}`)"
  >
    <div class="relative overflow-hidden bg-muted">
      <img
        :src="imageUrl"
        :alt="item.name"
        class="w-full h-auto object-contain group-hover:scale-105 transition-transform duration-500"
      >
      <div class="absolute top-2 right-2 flex flex-col gap-1 items-end">
        <UBadge
          v-if="item.status === 'sold'"
          color="neutral"
          variant="solid"
          size="sm"
        >
          Sold
        </UBadge>
      </div>
    </div>

    <div class="pt-3 flex flex-col gap-1.5 flex-1">
      <h3 class="font-semibold text-base line-clamp-1 group-hover:text-primary transition-colors">
        {{ item.name }}
      </h3>
      <p class="text-sm text-muted line-clamp-2 min-h-[2.5rem]">
        {{ item.condition }}
      </p>
    </div>

    <template #footer>
      <div class="flex flex-col">
        <span class="text-xs text-muted">Price</span>
        <span class="font-bold text-lg text-highlighted">
          RM {{ item.price?.toFixed(2) || '0.00' }}
        </span>
      </div>
      <UButton
        icon="i-lucide-arrow-right"
        size="sm"
        color="neutral"
        variant="ghost"
        class="group-hover:translate-x-1 transition-transform"
      />
    </template>
  </UCard>
</template>
